export const AB = {
  rausch: '#FF385C',
  babu: '#00A699',
  hack: '#FC642D',
  beach: '#FFB400',
  arches: '#914669',
  ink: '#222222',
  gray: '#717171',
  gray2: '#B0B0B0',
  border: '#EBEBEB',
  bg: '#F7F7F7',
  white: '#FFFFFF',
  page: '#F5F3EF',
};

export const LISTINGS = [
  {
    id: 'L1',
    name: 'Tampines Trilliant',
    unit: '#05-11',
    price: 'S$3,400',
    priceValue: 3400,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'Condo',
    area: 'Tampines',
    mrt: 'Tampines · 4min',
    mrtStation: 'Tampines',
    schoolZones: ['Angsana Primary 1km'],
    petFriendly: true,
    southFacing: true,
    commuteDrive: { 'one-north': 38 },
    tags: ['Pet-friendly', 'Angsana Pri 1km', 'South-facing'],
    agent: 'Rachel Ng',
    phone: '+65 9222 2222',
    cluster: 0,
    color: '#E07A5F',
  },
  {
    id: 'L2',
    name: 'Tampines Court',
    unit: '#12-08',
    price: 'S$3,250',
    priceValue: 3250,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'HDB',
    area: 'Tampines',
    mrt: 'Tampines · 7min',
    mrtStation: 'Tampines',
    schoolZones: ['Angsana Primary 1km'],
    petFriendly: false,
    renovated: true,
    commuteDrive: { 'one-north': 40 },
    tags: ['Angsana Pri 1km', 'Renovated'],
    agent: 'Kenneth Soh',
    phone: '+65 9333 3333',
    cluster: 0,
    color: '#E07A5F',
  },
  {
    id: 'L3',
    name: 'Bedok Residences',
    unit: '#09-22',
    price: 'S$3,600',
    priceValue: 3600,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'Condo',
    area: 'Bedok',
    mrt: 'Bedok · 2min',
    mrtStation: 'Bedok',
    schoolZones: [],
    petFriendly: false,
    highFloor: true,
    commuteDrive: { 'one-north': 35 },
    tags: ['High floor', 'Sea view'],
    agent: 'Sarah Lim',
    phone: '+65 9444 4444',
    cluster: 1,
    color: '#4C8577',
  },
  {
    id: 'L4',
    name: 'Bedok Grove',
    unit: '#03-05',
    price: 'S$3,150',
    priceValue: 3150,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'HDB',
    area: 'Bedok',
    mrt: 'Bedok · 6min',
    mrtStation: 'Bedok',
    schoolZones: [],
    petFriendly: true,
    renovated: true,
    commuteDrive: { 'one-north': 34 },
    tags: ['Pet-friendly', 'Renovated'],
    agent: 'James Wong',
    phone: '+65 9555 5555',
    cluster: 1,
    color: '#4C8577',
  },
  {
    id: 'L5',
    name: 'Queenstown View',
    unit: '#03-08',
    price: 'S$3,500',
    priceValue: 3500,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'HDB',
    area: 'Queenstown',
    mrt: 'Queenstown · 3min',
    mrtStation: 'Queenstown',
    schoolZones: ['Nanyang Primary 1km'],
    petFriendly: true,
    commuteDrive: { 'one-north': 18 },
    tags: ['Nanyang Pri 1km', 'one-north 18min', 'Pet-friendly'],
    agent: 'Priya Menon',
    phone: '+65 9666 6666',
    cluster: 2,
    color: '#4A6F8C',
  },
  {
    id: 'L6',
    name: 'Commonwealth Towers',
    unit: '#18-04',
    price: 'S$3,800',
    priceValue: 3800,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'Condo',
    area: 'Queenstown',
    mrt: 'Queenstown · 5min',
    mrtStation: 'Queenstown',
    schoolZones: [],
    petFriendly: true,
    highFloor: true,
    commuteDrive: { 'one-north': 12 },
    tags: ['Pool view', 'High floor', 'Pet-friendly'],
    agent: 'Daniel Koh',
    phone: '+65 9777 7777',
    cluster: 2,
    color: '#4A6F8C',
  },
  {
    id: 'L7',
    name: 'Bishan Loft',
    unit: '#10-03',
    price: 'S$3,000',
    priceValue: 3000,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'HDB',
    area: 'Bishan',
    mrt: 'Bishan · 6min',
    mrtStation: 'Bishan',
    schoolZones: ['Nanyang Primary 1km'],
    petFriendly: true,
    commuteDrive: { 'one-north': 29 },
    tags: ['Pet-friendly', 'Nanyang Pri 1km', 'one-north 29min'],
    agent: 'Melissa Yeo',
    phone: '+65 9888 1111',
    cluster: 3,
    color: '#8E6C88',
  },
  {
    id: 'L8',
    name: 'Sky Vue Residences',
    unit: '#15-07',
    price: 'S$3,350',
    priceValue: 3350,
    bed: '3BR',
    bedrooms: 3,
    propertyType: 'Condo',
    area: 'Bishan',
    mrt: 'Bishan · 4min',
    mrtStation: 'Bishan',
    schoolZones: ['Nanyang Primary 1km'],
    petFriendly: false,
    highFloor: true,
    commuteDrive: { 'one-north': 26 },
    tags: ['High floor', 'Nanyang Pri 1km'],
    agent: 'Alicia Tan',
    phone: '+65 9888 2222',
    listingUrl: 'https://www.propertyguru.com.sg/property-for-rent?market=residential&listing_type=rent&freetext=Sky%20Vue%20Residences',
    cluster: 3,
    color: '#8E6C88',
  },
];

export const TOURS = [
  { id: 'T1', buyer: 'Chen family', avatar: '陈', type: '3BR Rental', status: 'coordinating', progress: 4, total: 6, updated: '2 min ago', color: '#FF385C', preview: 'AI confirmed 4 of 6 viewings · Sarah Lim needs your call' },
  { id: 'T2', buyer: 'Rishi Patel', avatar: 'R', type: 'Condo · Sale', status: 'searching', progress: 0, total: 0, updated: '1h ago', color: '#00A699', preview: 'Awaiting client to pick shortlist' },
  { id: 'T3', buyer: 'Hazel Koh', avatar: 'H', type: 'HDB · Rental', status: 'confirmed', progress: 3, total: 3, updated: 'yesterday', color: '#FC642D', preview: 'Tour confirmed for Sun 7pm · sent to client' },
  { id: 'T4', buyer: 'Ng family', avatar: 'N', type: 'Landed · Sale', status: 'planning', progress: 0, total: 0, updated: '2d ago', color: '#914669', preview: 'Shortlist sent · waiting on availability' },
];

export const THREADS = [
  { id: 'th1', agent: 'Rachel Ng', avatar: 'R', unit: 'Tampines Trilliant', status: 'confirmed', color: '#E07A5F', time: 'Sat 10:00am', last: 'Yep, see u!' },
  { id: 'th2', agent: 'Kenneth Soh', avatar: 'K', unit: 'Tampines Court', status: 'confirmed', color: '#E07A5F', time: 'Sat 10:30am', last: 'ok confirmed' },
  { id: 'th3', agent: 'Sarah Lim', avatar: 'S', unit: 'Bedok Residences', status: 'exception', color: '#D93A4E', time: 'Conflict', last: 'only sun afternoon' },
  { id: 'th4', agent: 'James Wong', avatar: 'J', unit: 'Bedok Grove', status: 'confirmed', color: '#4C8577', time: 'Sat 11:45am', last: 'sure' },
  { id: 'th5', agent: 'Priya Menon', avatar: 'P', unit: 'Queenstown View', status: 'confirmed', color: '#4A6F8C', time: 'Sun 7:00pm', last: 'confirmed 👍' },
  { id: 'th6', agent: 'Daniel Koh', avatar: 'D', unit: 'Commonwealth Towers', status: 'confirmed', color: '#4A6F8C', time: 'Sun 7:45pm', last: 'confirmed' },
];

export const CHAT_RACHEL = [
  { from: 'ai', text: "Hi Rachel! I'm an AI assistant helping David Tan with scheduling. Is your unit at Tampines Trilliant #05-11 still available for rent?", ts: 'Fri 4:14 PM' },
  { from: 'them', text: 'Yes still available!', ts: 'Fri 4:21 PM' },
  { from: 'ai', text: "Great. My client: Senior Manager at a tech company, Singapore PR, couple with 5yo, 2yr lease, move-in June, no pets. OK with landlord?", ts: 'Fri 4:22 PM' },
  { from: 'them', text: 'Sounds fine, owner ok', ts: 'Fri 5:10 PM' },
  { from: 'ai', text: "Thanks! Which viewing slots work?\n1) Sat 9am–12pm\n2) Sat 3pm–6pm\n3) Sun 12pm–3pm", ts: 'Fri 5:11 PM' },
  { from: 'them', text: '1 and 3 work', ts: 'Fri 5:40 PM' },
  { from: 'ai', text: "Can we lock in Sat 10:00am? I'm pairing this with Tampines Court right after (3min walk).", ts: 'Sat 8:30 AM' },
  { from: 'them', text: 'Yep, see u!', ts: 'Sat 8:42 AM' },
];
